name: Bot

on:
  push:
    branches: [main]
    
jobs:
  telegram-trigger:
    name: 🚀 Launch parser via Telegram
    runs-on: ubuntu-latest
    steps:

      - name: 🔄 Checkout
        uses: actions/checkout@v4

      - name: 💾 Install parser dependencies
        run: |
          if [ -f requirements-parser.txt ]; then
            pip install -r requirements-parser.txt
          else
            echo "⚠️ requirements-parser.txt не найден — пропускаем установку"
          fi
          
      - name: 🔄 Checkout
        uses: actions/checkout@v4

      - name: 🧠 Load settings
        run: |
          echo "📥 Загрузка настроек"
          jq . settings.json

      - name: 🧹 Reset published.json if requested
        run: |
          if jq -e '.published_reset' settings.json > /dev/null; then
            echo "{}" > articles/published.json
            jq '.published_reset = false' settings.json > tmp && mv tmp settings.json
            echo "♻️ published.json сброшен"
          else
            echo "ℹ️ Сброс не требуется"
          fi
          
      - name: 🔐 WireGuard VPN setup
        run: |
          sudo apt-get update && sudo apt-get install -y wireguard-tools resolvconf jq curl
          mkdir -p $HOME/wg
          echo "${{ secrets.WG_CONFIG }}" > $HOME/wg/wg0.conf
          chmod 600 $HOME/wg/wg0.conf
          sudo wg-quick up $HOME/wg/wg0.conf
          echo "nameserver 1.1.1.1" | sudo tee /etc/resolv.conf

      - name: 💾 Install poster dependencies
        run: pip install -r requirements-poster.txt

      - name: 🔍 Run parser
        run: |
          BASE=$(jq -r '.base_url' settings.json)
          SLUG=$(jq -r '.slug' settings.json)
          LANG=$(jq -r '.lang' settings.json)
          python3 main.py --base-url "$BASE" --slug "$SLUG" --lang "$LANG"

      - name: 🛑 Teardown WireGuard
        if: always()
        run: sudo wg-quick down $HOME/wg/wg0.conf || true

      - name: 📤 Run poster
        run: |
          LIMIT=$(jq -r '.limit' settings.json)
          python3 poster.py --limit "$LIMIT"

      - name: 📡 Telegram Notify
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL }}
        run: |
          CHANNEL="${TELEGRAM_CHANNEL}"
          MESSAGE=$(jq -c . settings.json | sed 's/"/\\"/g')
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -d chat_id="$CHANNEL" \
            -d text="✅ Запуск завершён.\nПараметры:\n${MESSAGE}"
