# coding: utf-8
name: Telegram Bot CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
      # coding: utf-8
name: Telegram Bot CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyTelegramBotAPI

      - name: Lint Python
        run: |
          python -m py_compile cancel.py

      # Пример: запуск бота (раскомментируйте, если хотите запускать на CI, обычно только для теста)
      # - name: Run Bot (Dry Run)
      #   env:
      #     TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      #   run: |
      #     python your_script.py  run: |
          python -m pip install --upgrade pip
          pip install pyTelegramBotAPI

      - name: Lint Python
        run: |
          python -m py_compile cancel.py

      # Пример: запуск бота (раскомментируйте, если хотите запускать на CI, обычно только для теста)
      # - name: Run Bot (Dry Run)
      #   env:
      #     TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      #   run: |
      #     python your_script.py
