name: VPN Deployment Fix

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 */6 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install WireGuard
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard-tools linux-headers-$(uname -r)
          sudo modprobe wireguard

      - name: Configure WireGuard
        run: |
          sudo mkdir -p /etc/wireguard
          echo "${{ secrets.WG_CONFIG }}" > /tmp/wg0.conf
          
          # Strict validation
          if ! sudo wg-quick strip wg0 < /tmp/wg0.conf > /tmp/wg0_valid.conf; then
            echo "Invalid config:"
            cat /tmp/wg0.conf
            exit 1
          fi
          
          sudo mv /tmp/wg0_valid.conf /etc/wireguard/wg0.conf
          sudo chmod 600 /etc/wireguard/wg0.conf

      - name: Debug Pre-Connection
        run: |
          echo "Config file:"
          sudo cat /etc/wireguard/wg0.conf
          echo "Kernel modules:"
          lsmod | grep wireguard || true

      - name: Connect with Retry
        run: |
          for i in {1..3}; do
            sudo wg-quick up wg0 && break || sleep 5
            [ $i -eq 3 ] && exit 1
          done
          
          sudo wg show
          curl --interface wg0 --max-time 10 ifconfig.me

      - name: Main Application
        run: python bot.py

      - name: Cleanup
        if: always()
        run: sudo wg-quick down wg0 || true
