name: VPN Parser & Poster

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: 🧪 Проверка кеша установки
      id: setup_check
      run: |
        if [ -f "$HOME/.env_ready" ]; then
          echo "install_needed=false" >> $GITHUB_OUTPUT
        else
          echo "install_needed=true" >> $GITHUB_OUTPUT

    - name: 🛠️ Установка зависимостей (однократно)
      if: steps.setup_check.outputs.install_needed == 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y wireguard-tools resolvconf curl python3-pip
        pip3 install -U requests beautifulsoup4
        echo "done" > $HOME/.env_ready

    - name: 📁 Подготовка VPN-конфига
      run: |
        mkdir -p $HOME/wg
        echo "${{ secrets.WG_CONFIG }}" > $HOME/wg/wg0.conf
        chmod 600 $HOME/wg/wg0.conf

    - name: 🔐 Подключение WireGuard и DNS фиксация
      run: |
        sudo wg-quick up $HOME/wg/wg0.conf
        echo "nameserver 1.1.1.1" | sudo tee /etc/resolv.conf > /dev/null
        echo "VPN IP: $(curl -s https://ipinfo.io/ip)"

    - name: 🧠 Запуск парсера (main.py) под VPN
      run: |
        echo "→ Запускаем парсер main.py через VPN…"
        python3 main.py || echo "Парсер завершился с ошибкой"

    - name: 🛑 Отключение WireGuard
      if: always()
      run: |
        echo "→ Отключаем VPN…"
        sudo wg-quick down $HOME/wg/wg0.conf || echo "WireGuard уже отключён"

    - name: 📤 Запуск постера (poster.py)
      run: |
        echo "→ Запускаем постер poster.py…"
        python3 poster.py || echo "Постер завершился с ошибкой"
