name: VPN Parser & Poster with Cache

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: 💾 Кэширование зависимостей pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: 🛠️ Установка зависимостей
      run: |
        sudo apt-get update
        sudo apt-get install -y wireguard-tools resolvconf curl python3-pip
        pip3 install -r requirements.txt

    - name: 📁 Подготовка WireGuard конфига
      run: |
        mkdir -p $HOME/wg
        echo "${{ secrets.WG_CONFIG }}" > $HOME/wg/wg0.conf
        chmod 600 $HOME/wg/wg0.conf

    - name: 🔐 Подключение VPN и настройка DNS
      run: |
        sudo wg-quick up $HOME/wg/wg0.conf
        echo "nameserver 1.1.1.1" | sudo tee /etc/resolv.conf
        echo "VPN IP: $(curl -s https://ipinfo.io/ip)"

    - name: 🧠 Парсинг через VPN (main.py)
      run: |
        echo "→ Запускаем main.py..."
        python3 main.py || echo "⚠️ Парсер завершился с ошибкой"

    - name: 🛑 Отключение VPN
      if: always()
      run: |
        echo "→ Отключаем WireGuard..."
        sudo wg-quick down $HOME/wg/wg0.conf || echo "WireGuard уже завершён"

    - name: 📤 Постинг (poster.py)
      run: |
        echo "→ Запускаем poster.py..."
        python3 poster.py || echo "⚠️ Постер завершился с ошибкой"
