name: WireGuard VPN + CF Bypass

on:
  workflow_dispatch:

jobs:
  vpn-bypass:
    runs-on: ubuntu-latest

    steps:
    - name: 🔍 Проверка интернета
      run: |
        curl -s --connect-timeout 5 https://google.com \
          || { echo "Нет доступа к интернету"; exit 1; }

    - name: 📦 Установка пакетов
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          wireguard-tools \
          resolvconf \
          dnsutils \
          curl

    - name: 📁 Подготовка WireGuard конфига
      run: |
        mkdir -p $HOME/wg
        echo "${{ secrets.WG_CONFIG }}" > $HOME/wg/wg0.conf
        chmod 600 $HOME/wg/wg0.conf

    - name: 🔐 Подключение VPN и настройка DNS
      run: |
        sudo wg-quick up $HOME/wg/wg0.conf
        echo "nameserver 1.1.1.1" | sudo tee /etc/resolv.conf > /dev/null
        echo "VPN активен. Текущий IP: $(curl -s https://ipinfo.io/ip)"

    - name: 🛰 Получение IP через Cloudflare DNS
      id: resolve
      run: |
        DOMAIN="xn----ctbkymw5a2cwa.com"
        # получаем первый A-запись через 1.1.1.1
        IP=$(dig +short $DOMAIN @1.1.1.1 | head -n1)
        if [ -z "$IP" ]; then
          echo "Не удалось резолвить $DOMAIN" >&2
          exit 1
        fi
        echo "DOMAIN=$DOMAIN" >> $GITHUB_ENV
        echo "DOMAIN_IP=$IP" >> $GITHUB_ENV
        echo "$DOMAIN → $IP"

    - name: ⚔️ Действия под VPN с обходом DNS
      run: |
        # curl напрямую на полученный IP, подменяя Host-заголовок
        curl -s -A "Mozilla/5.0" \
          --resolve "${DOMAIN}:443:${DOMAIN_IP}" \
          -L "https://${DOMAIN}" \
          || echo "Запрос не прошёл"

    - name: 🛑 Отключение VPN
      if: always()
      run: |
        sudo wg-quick down $HOME/wg/wg0.conf || echo "WireGuard уже отключён"
