name: WireGuard VPN Quick Job

on:
  workflow_dispatch:

jobs:
  wg-vpn:
    runs-on: ubuntu-latest

    steps:
    - name: 🔍 Проверка подключения
      run: |
        curl -s --connect-timeout 5 https://google.com || {
          echo "Нет интернета"
          exit 1
        }

    - name: 📦 Установка WireGuard
      run: |
        sudo apt-get update
        sudo apt-get install -y wireguard-tools resolvconf nftables

    - name: 📁 Конфигурация VPN
      run: |
        mkdir -p $HOME/wg
        echo "${{ secrets.WG_CONFIG }}" > $HOME/wg/wg0.conf
        chmod 600 $HOME/wg/wg0.conf

    - name: 🔐 Подключение VPN + DNS Fix
      run: |
        sudo wg-quick up $HOME/wg/wg0.conf
        echo "nameserver 1.1.1.1" | sudo tee /etc/resolv.conf
        echo "IP под VPN:"
        curl -s -A "Mozilla/5.0" https://ipinfo.io/ip || echo "Cloudflare может блокировать"

    - name: ⚙️ Действия под VPN
      run: |
        echo "🚀 Сюда вставь команды, например:"
        curl -A "Mozilla/5.0" -L https://твоя-цель.com/api

    - name: 🛑 Отключение VPN
      if: always()
      run: |
        sudo wg-quick down $HOME/wg/wg0.conf || echo "WireGuard уже завершён"
