name: VPN Parser & Poster with Dependency Cache

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: 🛠️ Кэш Python-пакетов
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: 🧰 Установка зависимостей (однократно при изменении requirements.txt)
      run: |
        sudo apt-get update
        sudo apt-get install -y wireguard-tools resolvconf curl python3-pip
        pip3 install -r requirements.txt

    - name: 📁 Подготовка WireGuard конфига
      run: |
        mkdir -p $HOME/wg
        echo "${{ secrets.WG_CONFIG }}" > $HOME/wg/wg0.conf
        chmod 600 $HOME/wg/wg0.conf

    - name: 🔐 Подключение WireGuard и фиксация DNS
      run: |
        sudo wg-quick up $HOME/wg/wg0.conf
        echo "nameserver 1.1.1.1" | sudo tee /etc/resolv.conf
        echo "VPN активен. Текущий IP: $(curl -s https://ipinfo.io/ip)"

    - name: 🧠 Запуск парсера (main.py)
      run: |
        echo "→ Запуск main.py через VPN…"
        python3 main.py || echo "⚠️ Парсер завершился с ошибкой"

    - name: 🛑 Отключение WireGuard
      if: always()
      run: |
        echo "→ Отключаем VPN…"
        sudo wg-quick down $HOME/wg/wg0.conf || echo "VPN уже был отключён"

    - name: 📤 Запуск постера (poster.py)
      run: |
        echo "→ Запуск poster.py после VPN…"
        python3 poster.py || echo "⚠️ Постер завершился с ошибкой"
