name: WireGuard VPN Connectivity Test

on:
  workflow_dispatch:

env:
  TARGET_URL: https://www.khmertimeskh.com/wp-json/wp/v2/categories?slug=national

jobs:
  vpn-test:
    runs-on: ubuntu-latest

    steps:
    - name: 🔍 Проверка базового подключения
      run: |
        curl -s --connect-timeout 5 https://google.com -I \
          || { echo "Нет интернета"; exit 1; }

    - name: 📦 Установка WireGuard и утилит
      run: |
        sudo apt-get update
        sudo apt-get install -y wireguard-tools resolvconf dnsutils curl

    - name: 📁 Запись конфига WireGuard
      run: |
        mkdir -p $HOME/wg
        echo "${{ secrets.WG_CONFIG }}" > $HOME/wg/wg0.conf
        chmod 600 $HOME/wg/wg0.conf

    - name: 🔐 Поднятие VPN и фиксация DNS
      run: |
        sudo wg-quick up $HOME/wg/wg0.conf
        echo "nameserver 1.1.1.1" | sudo tee /etc/resolv.conf > /dev/null
        echo "VPN IP: $(curl -s https://ipinfo.io/ip)"

    - name: 🌐 Тест Google через VPN
      run: |
        echo "→ Testing https://www.google.com over VPN…"
        curl -v --connect-timeout 5 https://www.google.com -o /dev/null \
          || echo "⚠️ Google недоступен через VPN"

    - name: 🔗 Тест целевого URL через VPN
      run: |
        echo "→ Testing $TARGET_URL over VPN…"
        curl -v --connect-timeout 10 "$TARGET_URL" -o /dev/null \
          || echo "⚠️ Целевой URL недоступен через VPN"

    - name: 🛑 Отключение VPN
      if: always()
      run: |
        sudo wg-quick down $HOME/wg/wg0.conf || echo "VPN уже отключён"
