name: Simple WireGuard Fetch with Logging

on:
  workflow_dispatch:

jobs:
  fetch-via-vpn:
    runs-on: ubuntu-latest

    steps:
    - name: Установка WireGuard и утилит
      run: |
        sudo apt-get update
        sudo apt-get install -y wireguard-tools resolvconf curl

    - name: Подготовка WireGuard конфига
      run: |
        mkdir -p $HOME/wg
        echo "${{ secrets.WG_CONFIG }}" > $HOME/wg/wg0.conf
        chmod 600 $HOME/wg/wg0.conf

    - name: Поднятие VPN и фиксация DNS
      run: |
        sudo wg-quick up $HOME/wg/wg0.conf
        echo "nameserver 1.1.1.1" | sudo tee /etc/resolv.conf > /dev/null

    - name: Запрос целевого URL через VPN с логированием
      run: |
        TARGET="https://www.khmertimeskh.com/wp-json/wp/v2/categories?slug=national"
        echo "→ Попытка открыть сайт: $TARGET"
        RESPONSE=$(curl -s -w "\nHTTP_STATUS:%{http_code}" --connect-timeout 10 "$TARGET")
        echo "$RESPONSE"
        HTTP_STATUS=$(echo "$RESPONSE" | awk -F'HTTP_STATUS:' '/HTTP_STATUS/ {print $2}')
        if [ "$HTTP_STATUS" -eq 200 ]; then
          echo "✅ Успешно открыто через VPN (HTTP $HTTP_STATUS)"
        else
          echo "❌ Не удалось открыть через VPN (HTTP $HTTP_STATUS)"
          exit 1
        fi

    - name: Отключение VPN
      if: always()
      run: |
        sudo wg-quick down $HOME/wg/wg0.conf || echo "WireGuard уже отключён"
