name: WireGuard VPN Job

on:
  workflow_dispatch:

jobs:
  wireguard-vpn:
    runs-on: ubuntu-latest

    steps:
    - name: Проверка базового подключения к интернету
      run: |
        curl --connect-timeout 5 https://www.google.com || {
          echo "Нет доступа к интернету — возможен сбой runner'а"
          exit 1
        }

    - name: Установка WireGuard
      run: |
        sudo apt-get update
        sudo apt-get install -y wireguard-tools
        which wg-quick || {
          echo "Ошибка: wg-quick не установлен"
          exit 1
        }

    - name: Сборка WireGuard конфига
      run: |
        mkdir -p /etc/wireguard
        echo "${{ secrets.WG_CONFIG }}" > /etc/wireguard/wg0.conf
        sudo chmod 600 /etc/wireguard/wg0.conf

    - name: Запуск WireGuard
      run: |
        sudo wg-quick up wg0
        echo "VPN активен. Публичный IP:"
        curl https://ipinfo.io/ip

    - name: Действия под VPN
      run: |
        echo "Ваши команды здесь:"
        # Например:
        curl https://example.com/api/secure-data

    - name: Отключение WireGuard
      if: always()
      run: |
        sudo wg-quick down wg0 || echo "Не удалось отключить VPN — возможно, уже завершён"
