name: WireGuard VPN Workflow

on:
  workflow_dispatch:

jobs:
  use-wireguard:
    runs-on: ubuntu-latest

    steps:
    - name: 🔍 Проверка базового подключения к интернету
      run: |
        curl --connect-timeout 5 https://www.google.com || {
          echo "Нет интернета, остановка процесса."
          exit 1
        }

    - name: 📦 Установка WireGuard
      run: |
        sudo apt-get update
        sudo apt-get install -y wireguard-tools

    - name: 📁 Сборка локального WireGuard конфига
      run: |
        mkdir -p $HOME/wg
        echo "${{ secrets.WG_CONFIG }}" > $HOME/wg/wg0.conf
        chmod 600 $HOME/wg/wg0.conf

    - name: 🔐 Подключение VPN и настройка DNS
      run: |
        sudo wg-quick up $HOME/wg/wg0.conf
        echo "nameserver 1.1.1.1" | sudo tee /etc/resolv.conf > /dev/null
        echo "Публичный IP под VPN:"
        curl -s https://ipinfo.io/ip

    - name: ⚙️ Выполнение действий через VPN
      run: |
        echo "Добавьте сюда команды, например:"
         curl -X POST https://www.khmertimeskh.com/wp-json/wp/v2/categories?slug=national --data '...'
        # python3 bot.py --proxy-vpn-mode

    - name: 🛑 Отключение VPN
      if: always()
      run: |
        sudo wg-quick down $HOME/wg/wg0.conf || echo "WireGuard уже был завершён"
