name: WireGuard VPN

on:
  workflow_dispatch:

jobs:
  connect-vpn:
    runs-on: ubuntu-latest

    steps:
    - name: Проверка интернета
      run: ping -c 3 8.8.8.8 || exit 1

    - name: Установка WireGuard
      run: sudo apt-get update && sudo apt-get install -y wireguard

    - name: Сборка конфигурации WireGuard
      run: |
        mkdir -p /etc/wireguard
        echo "${{ secrets.WG_CONFIG }}" > /etc/wireguard/wg0.conf
        sudo chmod 600 /etc/wireguard/wg0.conf

    - name: Подключение к VPN
      run: sudo wg-quick up wg0

    - name: Действия через VPN
      run: curl https://ipinfo.io/ip

    - name: Отключение VPN
      if: always()
      run: sudo wg-quick down wg0
