name: WireGuard VPN Job

on:
  workflow_dispatch:

jobs:
  wireguard-vpn:
    runs-on: ubuntu-latest

    steps:
    - name: Проверка подключения
      run: |
        curl --connect-timeout 5 https://www.google.com || {
          echo "Нет интернета"
          exit 1
        }

    - name: Установка WireGuard
      run: |
        sudo apt-get update
        sudo apt-get install -y wireguard-tools

    - name: Сборка конфигурации в локальной директории
      run: |
        mkdir -p $HOME/wg
        echo "${{ secrets.WG_CONFIG }}" > $HOME/wg/wg0.conf
        chmod 600 $HOME/wg/wg0.conf

    - name: Подключение VPN с указанием пути
      run: |
        export WG_CONFIG_DIR="$HOME/wg"
        sudo wg-quick up wg0
        curl https://ipinfo.io/ip

    - name: Ваши действия
      run: echo "Тут можно выполнять команды под VPN"

    - name: Отключение VPN
      if: always()
      run: |
        export WG_CONFIG_DIR="$HOME/wg"
        sudo wg-quick down wg0 || echo "VPN уже завершён"
