name: VPN Bot Deployment
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 */6 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup WireGuard
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard-tools

      - name: Configure VPN
        env:
          WG_CONFIG: ${{ secrets.WG_CONFIG }}
        run: |
          sudo mkdir -p /etc/wireguard
          echo "$WG_CONFIG" | sudo tee /etc/wireguard/wg0.conf >/dev/null
          sudo chmod 600 /etc/wireguard/wg0.conf

      - name: Connect to VPN
        run: |
          sudo wg-quick up wg0
          sleep 5
          sudo wg show
