name: VPN Parser & Poster (No Cache)

on:
  workflow_dispatch:

jobs:
  run-via-vpn:
    runs-on: ubuntu-latest

    steps:
    - name: 🔄 Получение репозитория
      uses: actions/checkout@v4
      with:
        path: .

    - name: 🔧 Установка зависимостей
      run: |
        sudo apt-get update
        sudo apt-get install -y wireguard-tools resolvconf curl python3-pip
        pip3 install requests beautifulsoup4 Pillow python-telegram-bot

    - name: 📁 Подготовка WireGuard-конфига
      run: |
        mkdir -p $HOME/wg
        echo "${{ secrets.WG_CONFIG }}" > $HOME/wg/wg0.conf
        chmod 600 $HOME/wg/wg0.conf

    - name: 🔐 Подключение VPN и DNS
      run: |
        sudo wg-quick up $HOME/wg/wg0.conf
        echo "nameserver 1.1.1.1" | sudo tee /etc/resolv.conf
        echo "VPN IP: $(curl -s https://ipinfo.io/ip)"

    - name: 🧠 Запуск парсера (main.py)
      working-directory: .
      run: |
        echo "→ Запуск main.py..."
        python3 main.py || echo "⚠️ main.py завершился с ошибкой"

    - name: 🛑 Отключение VPN
      if: always()
      run: |
        echo "→ Отключение WireGuard..."
        sudo wg-quick down $HOME/wg/wg0.conf || echo "WireGuard уже выключен"

    - name: 📤 Запуск постера (poster.py)
      working-directory: .
      run: |
        echo "→ Запуск poster.py..."
        python3 poster.py || echo "⚠️ poster.py завершился с ошибкой"
