name: Telegram Bot + WireGuard

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # Каждые 6 часов

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    
      # 1. Загружаем код из репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # или другой нужный вам
          
      # 2. Установка WireGuard
      - name: Install WireGuard
        run: sudo apt-get update && sudo apt-get install -y wireguard resolvconf
        
      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Создание корректного конфига
      - name: Setup WireGuard config
        run: |
          sudo mkdir -p /etc/wireguard
          cat <<EOF | sudo tee /etc/wireguard/wg0.conf >/dev/null
          [Interface]
          PrivateKey = ${{ secrets.WG_PRIVATE_KEY }}
          Address = 10.66.66.2/32
          DNS = 1.1.1.1
          PostUp = ip route add 140.82.112.0/20 dev eth0
          PostUp = ip route add 185.199.108.0/22 dev eth0
          
          [Peer]
          PublicKey = ${{ secrets.WG_PUBLIC_KEY }}
          AllowedIPs = 0.0.0.0/0
          Endpoint = ${{ secrets.WG_ENDPOINT }}
          PersistentKeepalive = 25
          EOF
          sudo chmod 600 /etc/wireguard/wg0.conf
          
       # 5. Подключение VPN
      - name: Connect WireGuard
        run: |
          sudo wg-quick up wg0
          sleep 5
          sudo wg show
          curl --interface wg0 ifconfig.me

       # 6. Запускаем парсер (если нужен)
      - name: Run Parser
        run: python main.py  # или другой скрипт

       # 7. Отключение VPN
      - name: Disconnect WireGuard
        if: always()
        run: sudo wg-quick down wg0 || true
        

      # 78 Запуск бота
      - name: Run Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL }}
        run: python poster.py
